In [1]:
import sys
import os
sys.path.append("/home/milugu/ml_env/src/option_analyzer")
from data_utils.data_utils import DataManager
import logging

logging.basicConfig(format='%(levelname)s - %(name)s -: %(asctime)s %(message)s',
                    level=logging.INFO)

In [2]:
dm_spy = DataManager(api = 'alpha_vantage')

data = dm_spy.get_historical_data(symbol = 'SPY', interval = 'daily', start='01/05/2010')
data.head()

WARNING - Data Manager -: 2020-03-22 15:26:40,166 No attributes specified. Returning all columns!
WARNING - Data Manager -: 2020-03-22 15:26:40,170 No end date specified. Returning till the last row!
/home/milugu/ml_env/src/option_analyzer/data_utils/data_utils.py:121: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  data = raw_data.loc[row_range].copy()

,3. low,1. open,2. high,4. close,6. volume,5. adjusted close,8. split coefficient,7. dividend amount,EMA_H,EMA_L,...,OBV,Aroon_Down_H,Aroon_Up_H,Aroon_Down_L,Aroon_Up_L,SlowK,SlowD,SMA_H,SMA_L,Chaikin A/D
2010-01-05,112.85,113.26,113.68,113.63,111519230.0,92.4469,1.0,0.0,112.1789,111.1814,...,3.875750e+09,15.0,100.0,15.0,100.0,65.9551,56.1024,111.958,111.0540,7.476735e+09
2010-01-06,113.43,113.52,113.99,113.71,116017127.0,92.5120,1.0,0.0,112.3514,111.3956,...,3.991767e+09,10.0,100.0,10.0,100.0,94.6825,72.0698,112.081,111.2010,7.476735e+09
2010-01-07,113.18,113.50,114.33,114.19,130502017.0,92.9025,1.0,0.0,112.5398,111.5655,...,4.122269e+09,5.0,100.0,5.0,100.0,94.0952,84.9109,112.259,111.3965,7.575463e+09
2010-01-08,113.66,113.89,114.62,114.57,126357911.0,93.2116,1.0,0.0,112.7379,111.7650,...,4.248627e+09,0.0,100.0,0.0,100.0,94.2870,94.3549,112.481,111.6285,7.688659e+09
2010-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.shape

(3728, 40)